### ISSUE TITLE
Include CPUE trend for recent years?

### ISSUE THREAD

**Issue by seananderson** [seananderson/gfplot#17]
Likely 1996 onwards.

Could show raw CPUE and CPUE standardized according to a GLM similar to that used in many assessments (avoiding model selection though).

This may be more trouble than it's worth given issues unique to various stocks and the relevant spatial scale to do this at.

**Comment by seananderson** [comment]
Example standardization work: https://github.com/seananderson/pbs-synopsis/blob/master/R/tmb-hurdle.Rmd

**Comment by seananderson** [comment]
This is now set up in the R package to work for any fishery and management region. Started a quick vignette too:
https://sean.updog.co/Commercial-CPUE.html

**Comment by robynforrest** [comment]
Oh you are having too much fun
