### ISSUE TITLE
Try random effects maturity model

### ISSUE THREAD

**Issue by seananderson** [seananderson/gfplot#21]
- may end up being an academic exercise
- random intercept on sample ID?

**Comment by robynforrest** [comment]
I think so. Depends if we think fish in the same sample are independent. They may not have been living close together but have ended up in a net together. However, maybe they are more similar than fish caught from somewhere else on the coast ...

**Comment by seananderson** [comment]
Makes more of an impact than I would have thought. The thicker lines in the plots below are the fixed-effect estimates. The thin lines are the sample-ID-level random effect estimates. The first just has random intercepts and the second has random intercepts and slopes. There are also potentially time and location effects. Not a big effect on length at 50% maturity in this case, but it would affect L5 and L95.

![canary-mature-re-int](https://user-images.githubusercontent.com/19349/35465124-c928df98-02ae-11e8-9d7a-ef259edb1a8d.png)
![canary-mature-re-slope](https://user-images.githubusercontent.com/19349/35465125-c9404ed0-02ae-11e8-98f4-a2b155dd155a.png)

**Comment by robynforrest** [comment]
Nice! Do you think it is worth pursuing further? I'll see if I can find anything in the literature.

**Comment by seananderson** [comment]
This is implemented with `sample_id_re = TRUE` in `fit_mat_ogive()`, but defaults to `FALSE` for speed and consistency with existing analyses. There are a lot of samples for many species making the random effect estimation slow, even with TMB. Using random intercepts suggests that the intercepts (the proportion mature in each sample at the overall mean length given that length is centered) is drawn from a normal distribution, but that the slope (in logit space) is consistent across samples. My guess is that there is also a relationship between mean maturity in each sample and mean length in each sample, i.e., the random intercepts aren't entirely random. That could be checked by plotting the random intercepts against length. If there is a pattern then there should also be a group-level predictor for mean length for each sample (as in Gelman and Hill 2007).

Leaving this for now, but it would be interesting to come back to this someday when we have a particular stock in mind.

**Comment by robynforrest** [comment]
thanks Sean. could be a nice paper at some point
